<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <BaseOutputPath>..\bin\</BaseOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.8" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.12.0" /> 
  </ItemGroup>  

  <ItemGroup>
    <ProjectReference Include="..\Services\Events\Application\EventManagement.Events.Application.csproj" />
    <ProjectReference Include="..\Services\Events\Domain\EventManagement.Events.Domain.csproj" />
    <ProjectReference Include="..\Services\Events\Infrastructure\EventManagement.Events.Infrastructure.csproj" />    
    <ProjectReference Include="..\Services\Bookings\Application\EventManagement.Bookings.Application.csproj" />
    <ProjectReference Include="..\Services\Bookings\Domain\EventManagement.Bookings.Domain.csproj" />
    <ProjectReference Include="..\Services\Bookings\Infrastructure\EventManagement.Bookings.Infrastructure.csproj" />
    <ProjectReference Include="..\Services\Users\Application\EventManagement.Users.Application.csproj" />
    <ProjectReference Include="..\Services\Users\Domain\EventManagement.Users.Domain.csproj" />
    <ProjectReference Include="..\Services\Users\Infrastructure\EventManagement.Users.Infrastructure.csproj" />    
  </ItemGroup>  

</Project>